In [2]:
%pip install -U numpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 52.9 MB/s eta 0:00:00:00:01


  Attempting uninstall: numpy
    Found existing installation: numpy 2.3.1
    Uninstalling numpy-2.3.1:
      Successfully uninstalled numpy-2.3.1
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python -m pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.


In [3]:
import numpy as np

In [6]:
a = np.arange(24)
a.reshape((4,6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [9]:
np.random.seed(42)
a = np.arange(10)
b = np.arange(10)
np.random.shuffle(a)
np.random.shuffle(b)
print(a)
print(b)

[8 1 5 0 7 2 9 4 3 6]
[0 1 8 5 3 4 7 9 6 2]
